
[workspace]

members = [
    "array",
    "cargo",
    "conversion/from",
    "conversion/into",
    "conversion/string",
    "conversion/try_trait",
    "custom_types",
    "exe",
    "expression",
    "flow/for_loop",
    "hello"
]
